### ISSUE TITLE
Link hints for preview mode

### ISSUE THREAD

**Issue by erichalldev** [mrjackphil/obsidian-jump-to-link#1]
Let me start by saying this plugin is wonderful! I use Vimium every day and this is exactly what I was hoping for when the plugin API went live.

I generally prefer to navigate my notes in preview mode and this plugin only seems to work in source mode. I briefly looked into adding the functionality to get this to work in preview mode and it certainly isn't trivial as far as I can tell. Still, I wanted to create a feature request for this.

**Comment by mrjackphil** [comment]
Hi @erichalldev . Thanks for contribution! I'll check the PR when I'll be able. I had a quick look and I think it's fine. Script wasn't so big and was messy so a little bit refactor only helps.

**Comment by mrjackphil** [comment]
I published changed in 0.1.0
Thanks again!
