### ISSUE TITLE
Follow link in new pane

### ISSUE THREAD

**Issue by jtmusky** [mrjackphil/obsidian-jump-to-link#13]
Enhancement. Have the ability to follow a link by opening in a new pane.

**Comment by mrjackphil** [comment]
@jtmusky Hold `Shift` when pressing the link letter button. It should open a link in a new pane.

**Comment by jtmusky** [comment]
> @jtmusky Hold `Shift` when pressing the link letter button. It should open a link in a new pane.

Yep, holding `shift` opens a link in a new pane.
