### ISSUE TITLE
Vault internal Markdown links won't open

### ISSUE THREAD

**Issue by ChrisSimeon** [mrjackphil/obsidian-jump-to-link#16]
Hey, first of all: thanks for your great Plugin, I try to switch to keyboard only and links where one of the things where I still had to use the mouse. 

Unfotunately it seems that it doesn't work with markdown styled internal links. The [[Wikilinks]] work perfectly and so does external markdown links like `[David Hasselhoff](https://en.wikipedia.org/wiki/David_Hasselhoff)` but if internal links like `[David Hasselhof](../1%20Idols/Super%20Idols/David%20Hasselhoff.md)` does not work and gives me the following error:

main.ts:80 Uncaught (in promise) Error: Invalid URL
    at handleHotkey (eval at <anonymous> (app.js:1), <anonymous>:152:47)
    at HTMLDocument.handleKeyDown (eval at <anonymous> (app.js:1), <anonymous>:187:29)
handleHotkey @ main.ts:80
handleKeyDown @ main.ts:122

The link is valid if I command+click it or at least it finds the note in this case.

Is there a is there a bug or are my links just shit?

**Comment by mrjackphil** [comment]
Yep. Seems it doesn’t work correctly. Will fix this when will be able.

**Comment by ChrisSimeon** [comment]
Little update: I think it has to do with the fact that I chose relative paths in the settings and not absolute paths. Absolute Paths work in fact.

**Comment by mrjackphil** [comment]
@ChrisSimeon That's definitely is. I'm using relative paths, too. It open's a `My Computer` on my Windows machine :)

**Comment by mrjackphil** [comment]
@ChrisSimeon Should be fixed in 0.1.3
