### ISSUE TITLE
Add the ability to follow links generated by the query code block.

### ISSUE THREAD

**Issue by jtmusky** [mrjackphil/obsidian-jump-to-link#17]
Add the ability to follow links generated by the query code block.

Thanks for considering
-JM

**Comment by mrjackphil** [comment]
Hey, @jtmusky! Can you describe more precisely about that issue?)

**Comment by jtmusky** [comment]
I have some query code that looks like the following in obsidian.

````
```query
file:kb-
```
````
And it generates the files from the search query in preview. Is it possible to recognize those as links?
![image](https://user-images.githubusercontent.com/23535616/113889965-565a3c00-9789-11eb-9af0-d16589131719.png)

**Comment by mrjackphil** [comment]
@jtmusky I'm not sure about that. It'll need to rethink the plugin to work with Obsidian's UI.

As an alternative, I can suggest using [another plugin](https://github.com/mrjackphil/obsidian-text-expand) to expand blocks like this.

    ```expander
    file:kb-
    ```
it will generate something like this:
```
- [[KB-2021-03-19]] 
- [[KB-2021-03-20]]
- [[KB-2021-03-21]]
...
```

**Comment by jtmusky** [comment]
I'm going close this issue, I believe the expand plugin mentioned above is sufficient.
