### ISSUE TITLE
Feature Request: Jump to Dataview-rendered note links

### ISSUE THREAD

**Issue by frankreporting** [mrjackphil/obsidian-jump-to-link#19]
Love this plugin for bringing Vimium-like functionality to Obsidian's preview mode. I just discovered that it doesn't recognize notes/links rendered via the Dataview, another great plugin. Is it feasible to have Jump to Link "see" rendered lists and tables and find the links within them?

**Comment by aleksey-rowan** [comment]
This looks like a duplicate of https://github.com/mrjackphil/obsidian-jump-to-link/issues/28.

**Comment by frankreporting** [comment]
So it is. I'll close.
