### ISSUE TITLE
Jump to anywhere isn't working

### ISSUE THREAD

**Issue by asknet** [mrjackphil/obsidian-jump-to-link#21]
I tried this feature both as a keyboard shortcut and from command palette.

I'm on mac os and obsidian version is 0.12.4

Not sure what I missed here

**Comment by mrjackphil** [comment]
@asknet Hi, could you provide screenshots of plugin's settings menu and developer console after command execution?

**Comment by asknet** [comment]
Hi,
In edit mode it shows this error, whereas in preview mode nothing happens.
![2021-06-24_21-45-42 (1)](https://user-images.githubusercontent.com/1752644/123356589-f8422700-d535-11eb-914c-1ff84e9915da.gif)

**Comment by mrjackphil** [comment]
@asknet thanks for the repro. I'll check when will have some time. For now you can change the mode to the "popover" and check if it works there.

**Comment by mrjackphil** [comment]
Please, reopen the issue if error will appear again. Modal mode was removed so there should not be issue like was mentioned before.
