### ISSUE TITLE
FR: Recognise manually created links

### ISSUE THREAD

**Issue by SkepticMystic** [mrjackphil/obsidian-jump-to-link#24]
Similarly to issue #19, it would be awesome if Jump To Link would recognise non-standard wikilinks. For example, many plugins create manual links (Dataview, Breadcrumbs). My suggestion is that your plugin would pick up _any_ link with the `.internal-link` class. This would apply to all links, not just `a`nchor links

**Comment by mrjackphil** [comment]
@SkepticMystic it should work with latest release (0.5.0).
If there are any concrete problems - please reopen the issue or create another.
