### ISSUE TITLE
progressive filtering of locations with keystrokes

### ISSUE THREAD

**Issue by tallguyjenks** [mrjackphil/obsidian-jump-to-link#25]
Like easy motion it would be nice to see all the links on a page using "jump to anywhere" filter based on the first keystroke.

i cant take a screen shot of it but:

if the keys pop up and they're `aa` to `zz` then if my first kestroke is `e` then i'd like it to then ONLY show the `ea` through `ez` tooltips because the scope of where I want to go has been narrowed.

:)

**Comment by mrjackphil** [comment]
Should be possible because of amazing @jiyee in 0.5.1
