### ISSUE TITLE
[bug] should trim link on jump

### ISSUE THREAD

**Issue by ryzhovalex** [mrjackphil/obsidian-jump-to-link#26]
I create link to another file and use alter display name for it.

For example:
Edit mode:
![image](https://user-images.githubusercontent.com/72242438/139422583-08e25cb7-3ebe-41db-99d0-87139a8c490f.png)
Preview mode:
![image](https://user-images.githubusercontent.com/72242438/139422631-742a45d9-dd89-42cf-8d98-690bfbfb7b76.png)

I can easily open it by `ctrl+click` combination when i'm in editing mode and just by `click` in preview mode:
![image](https://user-images.githubusercontent.com/72242438/139423169-08a2bdb3-be5a-4522-8acd-780db46e6f66.png)

But when i use `ctrl+'` and type shortcut from panel, i get new created file:
![image](https://user-images.githubusercontent.com/72242438/139423126-b85286fa-ce0e-44f3-a584-d4b39c3731ce.png)

And each time i try to open this link that way, i new file creates:
![image](https://user-images.githubusercontent.com/72242438/139423767-ce87eaaf-f2f4-4c23-a097-8a7aa2c3b020.png)

----

I use only your plugin and support for Vimrc by community (+ Vim editor by Obsidian).

**Comment by mrjackphil** [comment]
Can you check if it will work with link without space before `|`?

**Comment by ryzhovalex** [comment]
> Can you check if it will work with link without space before `|`?

It works for option without space before.
![image](https://user-images.githubusercontent.com/72242438/139430538-0c2a152a-7088-4bb0-a6be-cd378920beca.png)

**Comment by mrjackphil** [comment]
@ryzhovalex So yeah, there is no trimming. Thanks for the bug report :)
