### ISSUE TITLE
Make it work on Dataview links

### ISSUE THREAD

**Issue by navakelvin** [mrjackphil/obsidian-jump-to-link#28]
It does not show popovers on Dataview links.

It only works (popovers appear) on [[WikiLinks]].

Can you make the first thing happen?

## How to recreate the problem:
1. Create a note
2. Create a WikiLink
3. Create a Dataview table
4. Run Jump To Link
5. You will see that it only places the popover on the wikilink.

**Comment by ArtemisFowl-San** [comment]
This actually works in reading view

**Comment by korniychuk** [comment]
First of all thanks to the author for this awesome plugin. It's amazing! I use the plugin countless times every day.

I'm waiting very much for Jump To Links to work in **Live Preview Mode**.

> This actually works in **reading view**

It would be super cool to make it work in the **Live Preview mode** also.

**Comment by zamlz** [comment]
I agree with @korniychuk! I too have been looking for a plugin like this and am super happy this exists! It seems to work great for defined links but unfortunately, like others have mentioned, it does not work for links created from dataview. I would greatly appreciate if this did become the case

**Comment by fredcallaway** [comment]
Any plans for this?

**Comment by mrjackphil** [comment]
@fredcallaway It might be done at some point. 

Maybe next year will be more generous with free time so I could tinker with it.
Or maybe a good Samaritan will land a PR. Who knows.

**Comment by mw9982** [comment]
Such a tremendously helpful and fast plugin as it is, and this feature would be the top. Thank you

**Comment by roman-balzer** [comment]
I created a pull request #62 for LivePreview support.

**Comment by mrjackphil** [comment]
Thank you, amazing @roman-balzer!
PR was merged and went to 0.5.0 release ✨
