### ISSUE TITLE
Not working on Pad/iOS

### ISSUE THREAD

**Issue by benhughes** [mrjackphil/obsidian-jump-to-link#29]
Do you know of any reason why this plugin won't work on iOS? Always comes up with the follwing error and I'm not too sure how to get proper error messages out in iOS.

![image](https://user-images.githubusercontent.com/1478194/149660420-e2f1a0cb-2aca-4d23-ad1d-085bcbcf5989.png)

Would love to use this on my iPad with the keyboard but can't work out why it crashes? Have checked it out locally and compared with some of my personal plugins and all seems OK.

Happy to make the changes myself was wondering if you knew of the reason before I start heading down rabbit holes.

**Comment by JenFau** [comment]
I have the same issue

**Comment by mrjackphil** [comment]
Please, check now. Latest update should work with CodeMirror 6. So it might work on mobile, too.

**Comment by tadashi-aikawa** [comment]
The reason seems that [it doesn't support Lookbehind in JS regular expressions for Safari](https://caniuse.com/js-regexp-lookbehind).

https://github.com/mrjackphil/obsidian-jump-to-link/blob/master/src/utils/common.ts#L65 (This is I added and created PR before 😅)

**Comment by mrjackphil** [comment]
It's a little bit hard for me to test. 
If someone have testing devices and can apply fixes - that would be nice.

**Comment by tadashi-aikawa** [comment]
@mrjackphil 
I have an iPad Pro and have fixed it just now 👍 I'll create PR. Please wait a moment :)

**Comment by tadashi-aikawa** [comment]
@mrjackphil 
I have created PR https://github.com/mrjackphil/obsidian-jump-to-link/pull/34 👍 

If anyone want to try it before the official release, please use BRAT and install [tadashi-aikawa/obsidian-sandbox](https://github.com/tadashi-aikawa/obsidian-sandbox/releases/tag/0.0.3).

**Comment by mrjackphil** [comment]
@tadashi-aikawa 
Approved and created a new version. 
Glad you're here, your help is priceless!

Would like to buy you a coffee. But I'm in a country from which I can't send/receive money to/from abroad.

**Comment by tadashi-aikawa** [comment]
@mrjackphil 
I just want to contribute to Obsidian, no need to care, but I'm glad you feel that way :) Thank you!
