### ISSUE TITLE
Changing the hotkey or having a command

### ISSUE THREAD

**Issue by FHachez** [mrjackphil/obsidian-jump-to-link#3]
Hey, 

I'm really interested in the plugin but `ctrl-' ` is already used for me 😅 
Do you plan to add a way to change the mapping?

An easy way would be to add an Obsidian Command, that we can remap easily in the Hotkeys setting. (I don't know if there is a performance difference, I wouldn't expect any).

Adding a command is quite easy: (I've hesitated to do a PR but it's not clear if I should start with master or the open PR).

```
this.addCommand({
			id: "jump-to-link",
			name: "Jump to link",
			callback: () => this.jumpToLink(),
			hotkeys: [],
		})
```

```
    jumpToLink() {
		let currentView: any = this.app.workspace.activeLeaf;
		let cmInst = currentView.view.sourceMode.cmEditor;

		if (!(currentView instanceof MarkdownView)) {
                    return
		}

		const urls = getUrlsFromText(cmInst);
		console.log('triggered')

		this.showJumpLetters(this.app, urls, cmInst)
  }
```

**Comment by mrjackphil** [comment]
Should be available in 0.1.0
Thanks @erichalldev
