### ISSUE TITLE
FR: Make `Jump-to-anywhere` type letters of the word to jump to

### ISSUE THREAD

**Issue by chrisgrieser** [mrjackphil/obsidian-jump-to-link#38]
Essentially, an implementation of lightspeed or sneak for vim, as proposed in #35 – curiously, the issue there was simply closed after @kohane27 achieved their goal, although the feature would indeed be quite useful to others

**Comment by kohane27** [comment]
@chrisgrieser

Hello! It was a very rudimentary implementation and I wasn't sure if anybody else would be interested. After fixing the bug I'll make a PR. Thanks!

**Comment by chrisgrieser** [comment]
Yes please, that would be wonderful <3

**Comment by kometenstaub** [comment]
I implemented #35, but it's just on my local machine for now. If @kohane27 and @mrjackphil are alright with it, I can PR it.

**Comment by kometenstaub** [comment]
Here's the commit if you want to take a look: https://github.com/kometenstaub/obsidian-jump-to-link/commit/128ef7aa9201a80ceb858c4cc89f8ad49800e835

**Comment by mrjackphil** [comment]
Closed by #39

**Comment by mrjackphil** [comment]
Thank you @kometenstaub for such a great work!
