### ISSUE TITLE
Open in new pane feature request

### ISSUE THREAD

**Issue by BrunoGomesCoelho** [mrjackphil/obsidian-jump-to-link#4]
Hi,

Thanks for the great plugin!

One feature I would love to see implemented is the option to open the new note in a new pane - This would greatly enhance navigating notes through Andy Mode and without a mouse.

Hopefully my time will free up by Christmas and I'll be able to send a PR, creating the issue just in case anyone else comes across the idea.

**Comment by erichalldev** [comment]
Hi @BrunoGomesCoelho, you can do this by pressing Shift plus the letter for the link. If there are two letters, you just need to press shift for one  of the letters.

**Comment by BrunoGomesCoelho** [comment]
Oops, I did try pressing shift but only before Ctrl, my bad! Thanks!
