### ISSUE TITLE
Ability to jump to native app uri schemes in Edit Mode

### ISSUE THREAD

**Issue by jeloi** [mrjackphil/obsidian-jump-to-link#48]
Hey there,

The plugin is able to recognize links that are not `https://`:

![image](https://user-images.githubusercontent.com/1616454/190934182-4f1c0d68-7af1-4a54-8401-9cafddb776d7.png)`
This seems to be for any non-standard url scheme, e.g: things:///show?id=VFh5iLZkuHkQZoTK7ib36L omnifocus://, etc

However, when triggering it via the "jump to link" hotkeys I get this error message:
![image](https://user-images.githubusercontent.com/1616454/190934278-c09e514c-db9d-4a93-aa21-c4d1d5ce259f.png)

We are able to visit these links both by clicking on them, and by using "jump to link" when in Preview Mode:
![image](https://user-images.githubusercontent.com/1616454/190934257-bd96812f-8faf-42e8-a203-ebbfd7bb549d.png)

It is just in Edit mode that this does not seem to be working.

Thank you for the great plugin.

**Comment by mrjackphil** [comment]
@jeloi Can't reproduce. Did fixes in 0.4.3. 
What's your plugin version?
Do you use **Live Preview** or legacy **Source mode**?

**Comment by mrjackphil** [comment]
Hey, feel free to reopen the issue if there are still problems with it.
