### ISSUE TITLE
[BUG] Jump to anywhere doesn't work for two character options

### ISSUE THREAD

**Issue by Archie-2021** [mrjackphil/obsidian-jump-to-link#49]
When i hit this option and lets say want to jump to "SE", when I hit S it just stops listening and it disappears leaving me where I was. It work for single character options tho.

I am on Windows 10 and using v0.15.09 obsidian

**Comment by PwrSunbucks** [comment]
I have the same issue with Jump to Anywhere.

I also have issue with Jump to Link. I press Jump to Link shortcut, letter prompt pops up over link, type single letter. No response

Linux obsidian v0.15.9

**Comment by OAGr** [comment]
Same. Using a mac, and 0.16.3.

**Comment by meangpu** [comment]
I also have same problem, **jump anywhere** work with one letter, but not with two letter
- using: Window 10, v.0.15.9
- use it with vim mode 
- if jump link is `DD` pop up disappear  when press first `D` and when press second `D` won't regcognize until exit jump anywhere mode / or press other popup character
here is the gif that show my problem
![problem](https://user-images.githubusercontent.com/51825872/193521007-661b954c-0a73-468e-8d3d-f30ce7e9c159.gif)

**Comment by mrjackphil** [comment]
Should be fixed in 0.4.4

**Comment by meangpu** [comment]
It fixed! Thank you so much! 😄

**Comment by Archie-2021** [comment]
> Should be fixed in 0.4.4


Thank you very much, it works now.
