### ISSUE TITLE
Popover remains when navigating by clicking.

### ISSUE THREAD

**Issue by retospect** [mrjackphil/obsidian-jump-to-link#5]
In popover mode, when I hit the hotkey, the popovers appear.
When I then click on a link with the mouse, the popovers remain in place and cover up the new page - until I hit a key on the keyboard.

**Comment by mrjackphil** [comment]
Should be fixed in v0.1.2

And thanks, @retospect for this issue. Feel free to reopen the issue if you still have problems with the plugin.
