### ISSUE TITLE
[Feature Request] add options for jump to link for opening  in new pane, tab and window

### ISSUE THREAD

**Issue by Archie-2021** [mrjackphil/obsidian-jump-to-link#54]
Please add options / hotkeys for jump to link for opening  in new pane, tab and window. I think the option for new tab is the most useful but other ones are going to be useful too. Thanks you.

**Comment by mrjackphil** [comment]
@Archie-2021 you should be able to open in new tab by holding Shift key before pressing the highlighted key.

**Comment by Archie-2021** [comment]
> @Archie-2021 you should be able to open in new tab by holding Shift key before pressing the highlighted key. 

Thanks

**Comment by mrjackphil** [comment]
Feel free to reopen issues or create another if you have any questions.
