### ISSUE TITLE
Does the "hold shift to select word" work for anyone?

### ISSUE THREAD

**Issue by yarub123** [mrjackphil/obsidian-jump-to-link#55]
When using the "⌃;" to jump to a word, I believe there is an option to hold "⇧" to "Select the word." Holding shift does nothing on my end. No big deal though, was just curious.

**Comment by mrjackphil** [comment]
@yarub123 when you hold shift you should be able open link in a new tab. Default behavior - open link in current tab.
Feel free to reopen issue or create another if you have more questions.

**Comment by yarub123** [comment]
Holy shit. I swear I didn't even notice. but today I randomly checked my notifications... Guess what date it is right NOW!!! (2/10/24, 10:43)  FEBRUARY 10th 2024.... holy SHIT does time friggin FLY. What the hell happened. 2020 was 4 years ago?!?! Maybe I was in a coma that I was unaware of... apologies for rambling. But yes. You're correct. I was confused as to the "select the word option." No worries. 

(The date thing was crazy because i looked at the time this issue was opend and it was exactly 1 year ago... what a goddamn trip)

Anyways, Peace be with you @mrjackphil ❤️

**Comment by mrjackphil** [comment]
@yarub123 Nice to hang out with you 😉
