### ISSUE TITLE
Lightspeed jump: jump to the middle of the word

### ISSUE THREAD

**Issue by aleksey-rowan** [mrjackphil/obsidian-jump-to-link#59]
Right now you can only jump to the beginning of the word with the Lightspeed jump since it's using the jump-to-anywhere logic. Is it possible to let you jump anywhere in the word with Lightspeed, like in the original nvim plugin?

**Comment by VoidAwake** [comment]
I've created a PR to add an option for this, but in the meantime you can just remove the `\\b` from line 584 of `.obsidian/plugins/mrj-jump-to-link/main.js`.

**Comment by mrjackphil** [comment]
Thanks @VoidAwake . 
PR merged in 0.5.3.
