### ISSUE TITLE
Let lightspeed jump or jump to anywhere work in visual mode.

### ISSUE THREAD

**Issue by langshangyuan** [mrjackphil/obsidian-jump-to-link#60]
The lightspeed or anywhere jump don't integrate smoothly with vim. In the Vim visual selection mode, I activate the jump to anywhere command, it will exit the visual mode first, and then jump to the desired location instead of selecting the content between the initial location and jumped location.

**Comment by VoidAwake** [comment]
Added in PR #51, you might need to reinstall the plugin to get the latest version.

**Comment by mrjackphil** [comment]
True, holding Shift should do the trick.
Thanks @VoidAwake for mention.

I'm closing the issue. Feel free to reopen or create another if there is a reason.
