### ISSUE TITLE
Error key-letters of mixed links in live preview mode

### ISSUE THREAD

**Issue by jiyee** [mrjackphil/obsidian-jump-to-link#64]
![image](https://github.com/mrjackphil/obsidian-jump-to-link/assets/787366/5c2cf533-37bb-4543-aeb8-2a6bcdb7c92f)

If normal links and live preview links mixed in page, key-letters has an error like above, the 'A' and 'Ax' occurs at the same time in page.

**Comment by mrjackphil** [comment]
While this concrete issue were fixed by #67 there are still #68 to fix.
