### ISSUE TITLE
Jump to Anywhere doesn't work.

### ISSUE THREAD

**Issue by neuromaancer** [mrjackphil/obsidian-jump-to-link#65]
As a vimer, I love this plugin! However, I found it doesn't work after version 0.5. I am not sure why, and I checked the console, there was no error. My obsidian version is v1.5.3. 

By the way, Jumy to Link works!

**Comment by mrjackphil** [comment]
@neuromaancer Hi, thanks for using plugin.
Just rolled 0.5.2 - should fix the issue. 
Feel free to reopen or create another issue if there will be a reason for it :)

**Comment by neuromaancer** [comment]
Hi, Thank you, it works!
