### ISSUE TITLE
Feature request: use the same layout for link hings as search term in Lightspeed

### ISSUE THREAD

**Issue by ksi** [mrjackphil/obsidian-jump-to-link#69]
My case: I use two layouts - latin and non-latin. If I use default link hints letters (all of them are latin) in lightspeed mode with non-latin search term it closes hints when I try to switch layout to select link. So I switched link hints to non-latin latters in the settings. No I can jump to non-latin links using non-latin keys. But now I cannot use it for latin words search :( 

The main issue here - hints are hidden when I switch keyboard layout. And an easy fix would be not hide them on layout switch. But even more elegant fix would be show hints in layout you use for search. Like I add both latin and non-latin letters to link hints, but show only for layout of typed search term.

**Comment by mrjackphil** [comment]
@ksi Could you record a video with a problem and screenshot your current settings?
I do too use two layouts (Latin and Non-Latin) but can't understand the problem.

**Comment by ksi** [comment]
Look. I've recorded an example here. The main problem I see: the plugin consumes all key pressed after it's own hotkey pressed. Two of them it uses as a search term for LightSpeed, then draws link hints and all other key pressed are interpreted as hints. And it is not something of it current hints - it just disables jump mode. But I have to press a key to switch layout from cyrillic I used as for search to Latin I use for hints. This is the CapsLock in my case. And after I press it - jump mode is being switched off. 

https://github.com/mrjackphil/obsidian-jump-to-link/assets/139096/be9f8076-e988-481a-a5f6-b382c3736991

**Comment by ksi** [comment]
Also I've noticed that LightSpeed mode works only if I disable "Jump to start of words" option. It looks like this mode uses some RegExp not working with non-latin.

**Comment by ksi** [comment]
Hi. No news? I think it is possible at least filter out layout switching key. Like don't count any strings out of alphabet except ESC in the `filterWithEventKey` method

**Comment by mrjackphil** [comment]
@ksi try now, hints shouldn't be hidden when you press `Ctrl`, `Shift`, `Scroll Lock` or `Caps Lock` keys which should be useful in your case.

While it might be better to fix the layout but it would need more effort.

**Comment by ksi** [comment]
It still does not work for me in 0.5.7. I looked at chageset. It looks like we should use whitelist by keycode of acceptable keyboard keys. I think in my case it does not work because of Linux and this: 
<img width="648" alt="image" src="https://github.com/mrjackphil/obsidian-jump-to-link/assets/139096/ab43e42b-72f7-4cb6-9776-b9d5abf53055">

**Comment by mrjackphil** [comment]
@ksi actually it shouldn't matter, because it uses codes from Electron on which Obsidian running. Which is system independent. 
But actually didn't test CapsLock because it remapped on my device. Let me check

**Comment by mrjackphil** [comment]
@ksi did you restart Obsidian after update?

**Comment by mrjackphil** [comment]
@ksi As far as I remember (didn't code for a while) KeyboardEvent.code in JS depends on V8 engine and not your OS. 
So, as we use the same Electron app, which is Obsidian, we shouldn't be bothered by this. 

Did you restart an Obsidian after update? There might be issues with correct unloading the app, I didn't check that precisely, unfortunately.

**Comment by ksi** [comment]
Yes, I restarted Obsidian. What did I notice. I unmapped keyboard layout switch from CapsLock. And now it does not cancel hint selection. Map back - cancels. Shift itself does not break hinting. Shift with keyboard layout switch - does. Maybe KDE Plasma works like: "If Caps is mapped to keyboard layout switch then send not CapsLock but some fixed code mapped to switch layout"? Anyway it looks like only whitelist will help here. And yes, I've read about keyCodes. You are completely right - the a too platform and even browser dependent. So the only way would be some dictionary between layouts or working with `keyboardLayoutMap()` (is it still experimental?). Or... some tricky heuristic like "compare key and its UpperCase". Will that give different values for CapsLock and other control keys? For legal keys it will do.

**Comment by mrjackphil** [comment]
@ksi You can help me to debug this.

You can:
1. Open Developer Tools (Ctrl+Shift+I)
2. Open `Console` tab
3. Run code `document.addEventListener("keydown", console.log)`
4. Try to replicate the issue. You'll see in console there will be KeyboardEvents for each key press. You can show me what events were executed.

The popovers should be hidden only if keys were pressed or there was a mouse click.

**Comment by ksi** [comment]
Hmm... It does not shows the event for CapsLock. 
<img width="769" alt="image" src="https://github.com/mrjackphil/obsidian-jump-to-link/assets/139096/4b22d2eb-c341-4034-94b2-8c9d1dea7271">

But single CapsLock looks like this: 
<img width="539" alt="image" src="https://github.com/mrjackphil/obsidian-jump-to-link/assets/139096/fac1df04-beca-4d45-80e4-a47ff4b7535e">
I think this is the exactly next keyboard layout group

**Comment by ksi** [comment]
Yep. All other combination for layout change gives the same key value. Like Shift+Shift or Win+space

**Comment by ksi** [comment]
Here how it looks in Win+Space case: 
<img width="584" alt="image" src="https://github.com/mrjackphil/obsidian-jump-to-link/assets/139096/defaa926-31ee-4c76-9c9b-f1e2b21caeac">

**Comment by mrjackphil** [comment]
@ksi Try 0.5.9 version

**Comment by ksi** [comment]
Yes, now this works! Thank you!
