### ISSUE TITLE
The obisidian.vimrc jumpToLink Lightspeed command no longer works as advertised

### ISSUE THREAD

**Issue by kjohnsen** [mrjackphil/obsidian-jump-to-link#75]
I followed the example on the README, but with Obsidian 1.7.4, pressing my hotkey pulls up the command palette with `:jumpToLink` and I have to press enter to complete the command. Before, it went straight to the jump.

```vimrc
exmap jumpToLink obcommand mrj-jump-to-link:activate-lightspeed-jump
nmap s :jumpToLink
vmap s :jumpToLink
```

**Comment by IamSmeagol** [comment]
Hi @kjohnsen I have the same issue. I think this is likely a result of the [obsidian vimrc](https://github.com/esm7/obsidian-vimrc-support ) plugin that the remapping relies on. It might be best to check with their repository instead.

I found someone who had the [same issue](https://github.com/esm7/obsidian-vimrc-support/issues/235#issuecomment-2426405437). The owner's solution is adding `<CR>` after the command.

**Comment by mrjackphil** [comment]
Thanks @IamSmeagol for deep dive and PR which reflects that in README. 
So I'll close that because of documentation change in #76

**Comment by kjohnsen** [comment]
Sounds good. Thank you both.
