### ISSUE TITLE
Make the keys a little more home-row friendly :)

### ISSUE THREAD

**Issue by fakeharxy** [mrjackphil/obsidian-jump-to-link#8]
Great plugin, the only thing I would really suggest is not to use straight alphabetical, I'd rather have to type two letters than ever use `z` or `o` in the link shortcut. 

Maybe focus on the home row first, then other easy to reach keys like `t` or `n` and then double up? I'm not sure if how vimium does it is available anywhere but that works pretty well?

Just a suggestion, obviously - it's already great!

**Comment by mrjackphil** [comment]
@fakeharxy that's actually a great idea, thanks. I think there were some thoughts in my mind by I forgot about it :)

**Comment by mrjackphil** [comment]
@fakeharxy So it should be fixed now. There are different default and option in settings menu which allows changing letters which used in link hints.
